### ISSUE TITLE
Suite test fails with python == 2.7.12

### ISSUE THREAD

**Issue by Starou** [Starou/SimpleIDML#37]
2.6.12

```
======================================================================
FAIL: test_add_pages_from_idml_to_template (regressiontests.idml.IdmlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tests/regressiontests/idml.py", line 3636, in test_add_pages_from_idml_to_template
    self.assertEqual(len(f.pages), 4)
AssertionError: 2 != 4
```

2.6.14 : 

```
======================================================================
FAIL: test_add_pages_from_idml (regressiontests.idml.IdmlTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tests/regressiontests/idml.py", line 3604, in test_add_pages_from_idml
    'Spreads/Spread_editoubd.xml']
AssertionError: Items in the first set but not the second:
'Spreads/Spread_editoub8.xml'
'Spreads/Spread_editoub7.xml'
Items in the second set but not the first:
'Spreads/Spread_editoubd.xml'
```

**Comment by Starou** [comment]
Fixed in Python3 support branch
